# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6662a0d93f9c0b3683deb965febb6d0edf09891ec6242296bf22a198c0d6b93e26438bb9e89469bda76346a8477459c5e8b6d74746656176ad90fcd6f9223541

test:
  secret_key_base: 275ddaf2dc27fd23cc97b9abfec6fb7f3cd1d53ef100476997ec8995d40be0bb46e1df3db4cf922223fe80c1f1f5b0d932c83230d1f27cd2523e6674cd28294c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
